dataListSample = {
    "CATEGORIES" : ["HOTEL BREAKFAST", "HOTEL LUNCH", "HOTEL DINNER", "SNACKS", "NON VEG", "VEGETABLES / FRUITS", 
        "GROCERY", "TRAVEL", "INSURANCE","DOCTOR / HOSPITAL", "MEDICINE", "SHOPPING", "UTILITY EXPENSE"
    ],

    "HOTEL BREAKFAST" : ["HOTEL BREAKFAST", "OTHERS"],
    
    "HOTEL LUNCH" : ["HOTEL LUNCH", "OTHERS"],
   
    "HOTEL DINNER" : ["HOTEL DINNER", "OTHERS"],
    
    "SNACKS" : ["SNACKS", "VADA"],
    
    "NON VEG" : ["NON VEG", "MUTTON", "CHICKEN", "FISH"],

    "VEGETABLES / FRUITS" : ["VEGETABLES / FRUITS", "VEGETABLES", "FRUITS"],

    "GROCERY" : ["GROCERY"],

    "TRAVEL" : ["TRAVEL"],

    "INSURANCE" : ["LIC", "CAR INSURANCE", "BIKE INSURANCE", "HEALTH INSURANCE"],

    "DOCTOR / HOSPITAL" : ["DOCTOR / HOSPITAL"],
    
    "MEDICINE" : ["MEDICINE"],

    "SHOPPING" : ["SHOPPING", "CLOTHES", "FURNITURE", "ELECTRONICS/ELECTRICALS", "HOUSEHOLD ITEMS", "OTHERS"],

    "UTILITY EXPENSE" : ["PETROL", "HAIRCUT", "IRON CLOTHES", "EB BILL", "GAS BILL", "PROPERTY TAX", "WATER TAX", "SEWAGE TAX", "CAR SERVICE", "BIKE SERVICE", 
        "PLUMBING/ELECTRICAL", "FASTTAG", "OTHERS"],

    "DATA" : [
            [ "2025-01-31", "MEDICINE", "MEDICINE", 1120 ],
            [ "2020-03-30", "NON VEG", "MUTTON", 679 ],
            [ "2022-02-25", "TRAVEL", "TRAVEL", 54 ],
            [ "2025-04-11", "GROCERY", "GROCERY", 5678 ],
        ]
};

function returnDataList() {
    return dataListSample;
}